// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAppTb01Lab01_LC.Models;

namespace WebAppTb01Lab01_LC.Migrations
{
    [DbContext(typeof(AutomovelContext))]
    [Migration("20180409185010_CriaBanco")]
    partial class CriaBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppTb01Lab01_LC.Models.Automovel", b =>
                {
                    b.Property<int>("AutomovelId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<bool>("Disponivel");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<int>("Tipo");

                    b.HasKey("AutomovelId");

                    b.ToTable("Automovel");
                });
#pragma warning restore 612, 618
        }
    }
}
